import { compile } from "json-schema-to-typescript";
import { format, resolveConfig } from "prettier";
import {
  mkdtemp,
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const packageDirectory = resolve(scriptDirectory, "..");
const repositoryRoot = resolve(packageDirectory, "../..");
const schemaDirectory = join(packageDirectory, "schemas");
const generatedDirectory = join(packageDirectory, "src", "generated");
const canonicalBase = "https://thermiteschematics.com/schemas/0.1/";

const banner = `/**
 * Generated from the canonical Thermite Schematics JSON Schemas.
 * Do not edit this file directly; run npm run generate:types.
 */
`;

const roots = [
  { schema: "cable.schema.json", output: "cable.ts", name: "Cable" },
  {
    schema: "cable-type.schema.json",
    output: "cable-type.ts",
    name: "CableType",
  },
  { schema: "device.schema.json", output: "device.ts", name: "Device" },
  {
    schema: "device-type.schema.json",
    output: "device-type.ts",
    name: "DeviceType",
  },
  { schema: "jumper.schema.json", output: "jumper.ts", name: "Jumper" },
  {
    schema: "library.schema.json",
    output: "library.ts",
    name: "LibraryManifest",
  },
  {
    schema: "library-file.schema.json",
    output: "library-file.ts",
    name: "LibraryFile",
  },
  {
    schema: "library-lock.schema.json",
    output: "library-lock.ts",
    name: "LibraryLock",
  },
  {
    schema: "potential.schema.json",
    output: "potential.ts",
    name: "Potential",
  },
  {
    schema: "project.schema.json",
    output: "project.ts",
    name: "ProjectManifest",
  },
  {
    schema: "project-presentation.schema.json",
    output: "project-presentation.ts",
    name: "ProjectPresentationFile",
  },
  {
    schema: "relation.schema.json",
    output: "relation.ts",
    name: "Relation",
  },
  {
    schema: "source-file.schema.json",
    output: "source-file.ts",
    name: "SourceFile",
  },
  { schema: "wire.schema.json", output: "wire.ts", name: "Wire" },
];

const deviceFunctionTypes = [
  "CoilFunction",
  "ContactFunction",
  "ChannelFunction",
  "SourceFunction",
  "LoadFunction",
  "BusFunction",
  "MechanismFunction",
  "OtherFunction",
];

function normalizeLf(source) {
  const normalized = source.replaceAll("\r\n", "\n").replaceAll("\r", "\n");
  return normalized.endsWith("\n") ? normalized : `${normalized}\n`;
}

async function loadSchemas() {
  const fileNames = (await readdir(schemaDirectory))
    .filter((fileName) => fileName.endsWith(".schema.json"))
    .sort();
  const expectedFileNames = [
    ...roots.map(({ schema }) => schema),
    "common.schema.json",
  ].sort();

  if (JSON.stringify(fileNames) !== JSON.stringify(expectedFileNames)) {
    throw new Error(
      `Canonical schema inventory differs from the generator inventory.\nExpected: ${expectedFileNames.join(", ")}\nActual: ${fileNames.join(", ")}`,
    );
  }

  const schemas = new Map();
  for (const fileName of fileNames) {
    const localPath = join(schemaDirectory, fileName);
    const schema = JSON.parse(await readFile(localPath, "utf8"));
    const expectedId = `${canonicalBase}${fileName}`;

    if (schema.$id !== expectedId) {
      throw new Error(
        `${fileName} has $id ${JSON.stringify(schema.$id)}, expected ${JSON.stringify(expectedId)}.`,
      );
    }

    schemas.set(expectedId, { localPath, schema });
  }

  for (const { schema: fileName, name } of roots) {
    const document = schemas.get(`${canonicalBase}${fileName}`)?.schema;
    if (document?.title !== name) {
      throw new Error(
        `${fileName} has title ${JSON.stringify(document?.title)}, expected ${JSON.stringify(name)}.`,
      );
    }
  }

  const common = schemas.get(`${canonicalBase}common.schema.json`)?.schema;
  if (
    common === undefined ||
    common.type !== undefined ||
    common.title !== undefined
  ) {
    throw new Error(
      "common.schema.json must remain an untitled definitions-only document.",
    );
  }

  return schemas;
}

function canonicalResolver(schemas) {
  return {
    order: 1,
    canRead(file) {
      try {
        const url = new URL(file.url);
        return (
          url.protocol === "https:" &&
          url.origin === "https://thermiteschematics.com" &&
          url.pathname.startsWith("/schemas/0.1/")
        );
      } catch {
        return false;
      }
    },
    async read(file) {
      const url = new URL(file.url);
      url.hash = "";
      const entry = schemas.get(url.href);
      if (entry === undefined) {
        throw new Error(`Rejected unknown canonical schema URI: ${url.href}`);
      }
      return readFile(entry.localPath, "utf8");
    },
  };
}

function generatorOptions(schemas, prettierConfig) {
  return {
    $refOptions: {
      resolve: {
        file: false,
        http: false,
        canonical: canonicalResolver(schemas),
      },
    },
    bannerComment: banner,
    cwd: schemaDirectory,
    format: false,
    strictIndexSignatures: true,
    style: { ...prettierConfig, endOfLine: "lf" },
    unreachableDefinitions: true,
    unknownAny: true,
  };
}

function hasNamedExport(source, name) {
  return (
    source.includes(`export interface ${name}`) ||
    source.includes(`export type ${name}`)
  );
}

function deviceFunctionSurface() {
  return `
export type DeviceFunction = ${deviceFunctionTypes.join(" | ")};

export type ValidatedDeviceType = Omit<DeviceType, "functions"> & {
  functions: Record<string, DeviceFunction>;
};
`;
}

async function formatTypeScript(source, output, prettierConfig) {
  return normalizeLf(
    await format(source, {
      ...prettierConfig,
      endOfLine: "lf",
      filepath: output,
      parser: "typescript",
    }),
  );
}

async function assertResolverPolicy(schemas, prettierConfig) {
  const options = generatorOptions(schemas, prettierConfig);
  await compile(
    { $ref: `${canonicalBase}common.schema.json#/$defs/uid` },
    "CanonicalResolverProbe",
    options,
  );

  for (const ref of [
    `${canonicalBase}missing.schema.json`,
    "https://example.com/remote.schema.json",
  ]) {
    let rejected = false;
    try {
      await compile({ $ref: ref }, "RejectedRemote", options);
    } catch (error) {
      if (error?.source !== ref && !String(error).includes(ref)) {
        throw error;
      }
      rejected = true;
    }

    if (!rejected) {
      throw new Error(`The offline resolver unexpectedly accepted ${ref}.`);
    }
  }
}

function generatedBarrelSource() {
  const lines = roots.map(
    ({ output, name }) =>
      `export type { ${name} } from "./${output.replace(/\.ts$/, ".js")}";`,
  );
  lines.push(
    `export type {\n  ${deviceFunctionTypes.join(",\n  ")},\n  DeviceFunction,\n  ValidatedDeviceType,\n} from "./device-type.js";`,
  );
  return `${banner}\n${lines.join("\n")}\n`;
}

function canonicalSchemasSource(schemas) {
  const records = [...schemas.entries()].map(([id, { schema }]) => {
    const fileName = new URL(id).pathname.split("/").at(-1);
    if (fileName === undefined || fileName === "") {
      throw new Error(`Canonical schema id has no filename: ${id}.`);
    }
    return `  {\n    fileName: ${JSON.stringify(fileName)},\n    id: ${JSON.stringify(id)},\n    schema: ${JSON.stringify(schema, undefined, 2)},\n  }`;
  });
  return `${banner}\nimport type { LoadedSchema } from "../schema-registry.js";\n\nexport const IN_MEMORY_CANONICAL_SCHEMAS: readonly LoadedSchema[] = [\n${records.join(",\n")}\n];\n`;
}

export async function generateFiles() {
  const schemas = await loadSchemas();
  const prettierConfig =
    (await resolveConfig(join(repositoryRoot, "package.json"))) ?? {};
  await assertResolverPolicy(schemas, prettierConfig);
  const options = generatorOptions(schemas, prettierConfig);
  const files = new Map();

  for (const root of roots) {
    const schema = schemas.get(`${canonicalBase}${root.schema}`)?.schema;
    let source = await compile(schema, root.name, options);
    if (root.schema === "device-type.schema.json") {
      source += deviceFunctionSurface();
    }
    source = await formatTypeScript(source, root.output, prettierConfig);

    if (!hasNamedExport(source, root.name)) {
      throw new Error(`${root.output} does not export ${root.name}.`);
    }
    files.set(root.output, source);
  }

  const deviceTypeSource = files.get("device-type.ts") ?? "";
  for (const name of [
    ...deviceFunctionTypes,
    "DeviceFunction",
    "ValidatedDeviceType",
  ]) {
    if (!hasNamedExport(deviceTypeSource, name)) {
      throw new Error(`device-type.ts does not export ${name}.`);
    }
  }

  files.set(
    "index.ts",
    await formatTypeScript(generatedBarrelSource(), "index.ts", prettierConfig),
  );
  files.set(
    "canonical-schemas.ts",
    await formatTypeScript(
      canonicalSchemasSource(schemas),
      "canonical-schemas.ts",
      prettierConfig,
    ),
  );
  return files;
}

async function writeGeneratedFiles(directory, files) {
  await mkdir(directory, { recursive: true });
  const expectedNames = new Set(files.keys());
  const existingNames = await readdir(directory);

  for (const existingName of existingNames) {
    if (!expectedNames.has(existingName)) {
      await rm(join(directory, existingName), { recursive: true, force: true });
    }
  }

  for (const [fileName, source] of files) {
    await writeFile(join(directory, fileName), source, "utf8");
  }
}

async function compareGeneratedDirectories(expectedDirectory, actualDirectory) {
  const expectedNames = (await readdir(expectedDirectory)).sort();
  let actualNames;
  try {
    actualNames = (await readdir(actualDirectory)).sort();
  } catch (error) {
    if (error?.code === "ENOENT") {
      throw new Error(
        `Generated types are missing. Run npm run generate:types.`,
      );
    }
    throw error;
  }

  if (JSON.stringify(expectedNames) !== JSON.stringify(actualNames)) {
    throw new Error(
      `Generated type file inventory drifted. Run npm run generate:types.\nExpected: ${expectedNames.join(", ")}\nActual: ${actualNames.join(", ")}`,
    );
  }

  const changed = [];
  for (const fileName of expectedNames) {
    const [expected, actual] = await Promise.all([
      readFile(join(expectedDirectory, fileName)),
      readFile(join(actualDirectory, fileName)),
    ]);
    if (!expected.equals(actual)) changed.push(fileName);
  }

  if (changed.length > 0) {
    throw new Error(
      `Generated types are stale: ${changed.join(", ")}. Run npm run generate:types.`,
    );
  }
}

async function checkGeneratedFiles(files) {
  const temporaryDirectory = await mkdtemp(
    join(tmpdir(), "thermite-schematics-generated-types-"),
  );
  try {
    await writeGeneratedFiles(temporaryDirectory, files);
    await compareGeneratedDirectories(temporaryDirectory, generatedDirectory);
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
}

export async function checkCommittedGeneratedFiles() {
  await checkGeneratedFiles(await generateFiles());
}

async function main() {
  const arguments_ = process.argv.slice(2);
  if (arguments_.some((argument) => argument !== "--check")) {
    throw new Error(`Unknown argument: ${arguments_.join(" ")}`);
  }

  if (arguments_.includes("--check")) {
    await checkCommittedGeneratedFiles();
    console.log("Generated schema types are up to date.");
  } else {
    const files = await generateFiles();
    await writeGeneratedFiles(generatedDirectory, files);
    console.log(
      `Generated ${String(files.size)} files in ${basename(generatedDirectory)}.`,
    );
  }
}

const invokedPath = process.argv[1];
if (
  invokedPath !== undefined &&
  import.meta.url === pathToFileURL(resolve(invokedPath)).href
) {
  await main();
}
